[package]
name = "htmd"
version = "0.2.0"
edition = "2021"
authors = ["letmutex"]
description = "A turndown.js inspired HTML to Markdown converter."
license = "Apache-2.0"
repository = "https://github.com/letmutex/htmd"
homepage = "https://github.com/letmutex/htmd"
keywords = ["html", "markdown", "converter"]
categories = ["text-processing", "parsing"]
readme = "README.md"

[dependencies]
html5ever = "0.29.1"
markup5ever_rcdom = "0.5.0-unofficial"
html-escape = "0.2.13"

[dev-dependencies]
scraper = "0.23.1"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "convert_bench"
harness = false
